### ISSUE TITLE
Countdown doesn't take look at years

### ISSUE THREAD

**Issue by MeMeBigProgrammer** [MyMICDS/MyMICDS-v2-Angular#105]
The countdown module doesn't look at years, only dates, reading to incorrect results.

**Comment by nickbclifford** [comment]
As in it doesn't take years into account at all? So a countdown to March 22, 2021 would show 60 days instead of 425 days?

**Comment by MeMeBigProgrammer** [comment]
yeah, a friend of mine put a countdown to April 20th, 2069, and it says 72 days until. I've gotten the same results when I tested it on prod.

**Comment by nickbclifford** [comment]
Interesting, I'll take a look at it.

**Comment by michaelgira23** [comment]
Perhaps it is [this line](https://github.com/MyMICDS/MyMICDS-v2-Angular/blob/c94ffe71c6f3200e43178c235bbda44e920d3ee8/src/app/components/modules/countdown/countdown.component.ts#L202) that I originally wrote with the intention of getting the difference of time in terms of days (because we do not display any other unit), rather than getting the 'days' unit of the difference. There might be another method to accomplish the original goal.

**Comment by nickbclifford** [comment]
Judging from the moment [docs](https://momentjs.com/docs/#/durations/diffing/), we might want to do `moment.duration(targetDate.diff(moment())).as('days')`.

**Comment by MeMeBigProgrammer** [comment]
Turns out the user (and I) had the "only count school days" button checked. I'm closing this issue. 

My b
