### ISSUE TITLE
Show when Canvas last refreshed

### ISSUE THREAD

**Issue by nickbclifford** [MyMICDS/MyMICDS-v2-Angular#99]
Currently, we do have a "Refresh Canvas" button, but sometimes I worry that people don't think to use it and then do the wrong homework, especially during schedule changes (like our last two snowdays). To help with this, I think it'd be a good idea to put an indicator somewhere on the sidebar showing when the Canvas feed was last updated.

This might need backend changes to store a `createdAt` timestamp, although I think we might be able to take advantage of the ObjectIDs that are part of the `PlannerEvent` object and retrieve the time from that.

My first thought is a `float: right;` next to the Coming Up header:
![image](https://user-images.githubusercontent.com/11001606/71015059-9b4ff000-20b8-11ea-9310-7d18d9271c61.png)
(this was just done with Inspect Element)

We could also use a flexbox if we wanted to be more flexible with positioning.

**Comment by michaelgira23** [comment]
Mongo Object IDs may be possible, but I thought I remember reading that we should never really on that (because spec doesn't ensure or might change in future or something?) A `createdAt` parameter would be best. 

Otherwise, this seems helpful! Another possibility is to trigger a canvas refresh once the user logs on for the first time that day
